on:
  # Trigger the workflow on a successful merge
  # but only for the main branch
  push:
    branches:
      - main
    paths: 
      - data/**
    # paths-ignore: # Don't trigger on files that are updated by the CI
    #  - '.gitignore'
    #  - 'README.md'
    #  Note: used to trigger on all changes EXCEPT for a few files.  
    #        Changing this to only run when the data file is changed
 
jobs:
  render-index:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.0.2' # The R version to download (if necessary) and use.
    - uses: r-lib/actions/setup-pandoc@v2
    - name: Run gh_actions_run_script.R
      run: Rscript ./scripts/gh_actions_run_script.R
    - name: commit rendered files
      run: |
        git config --local user.name github-actions
        git config --local user.email "actions@github.com"
        git add --all
        git commit -m "Adding new html files via gh actions"
        git push origin main 
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
